---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luochen.
--- DateTime: 2018/6/16 10:10
---



local file = io.open("conf/nginx-gateway.conf","rb")

local contents
if file then
    contents = file:read("*all")
    file:close()

end

print(contents)


