---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luochen.
--- DateTime: 2018/6/2 11:11
---
local cjson = require("cjson")

local _M = {}


    function _M.encode(data, empty_table_as_object)
        if not data then return nil end

        if cjson.encode_empty_table_as_object then
            -- empty table default is arrya
            cjson.encode_empty_table_as_object(empty_table_as_object or false)
        end



        return cjson.encode(data)
    end

    function _M.decode(data)
        if not data then return nil end

        return cjson.decode(data)
    end

return _M;

